### ISSUE TITLE
More info on planet info panel

### ISSUE THREAD

**Issue by PBWiseman** [BIT-Studio-3/Space-Rescue#174]
**Description:**
The planet should have information about the number of animals left and what types of animals are on the planet. This will need to be done after the planet state info is completed.

**User Story:**
As a completionist, I want to know what animals are on the planet, so I can get ones I haven't found yet.

**Comment by erokasyuart** [comment]
### User Story
As a player, I want to see how many remaining animals are on a planet so I can find them easier
As a player, I want to see what kind of animals I've caught because I want an easier and visual way to keep track.

### Description
On the planet, the panel will be filled with icons of the animal models as they are collected, and will be removed when deposited into the drop ship and update the score. I will use Palin's save script to make it unique to every planet.

I will also add a "scanner" or some indication to the player about where remaining animals are on the planet. I think this should have a cooldown so the player doesn't exploit it.
